services:
  karly.api:
    build:
      dockerfile: ./src/Karly.Api/Dockerfile
    ports:
      - "8080:8080"
  database:
    image: postgres:17.1
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:5432"
