services:
  karly.api:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    tty: true
    entrypoint:
      /bin/bash -c "dotnet restore && dotnet watch run --no-launch-profile --project ./src/Karly.Api"
    working_dir: /karly-api
    volumes:
      - .:/karly-api
      - karly_api_bin_volume:/karly-api/src/Karly.Api/bin
      - karly_api_obj_volume:/karly-api/src/Karly.Api/obj
      - karly_application_bin_volume:/karly-api/src/Karly.Application/bin
      - karly_application_obj_volume:/karly-api/src/Karly.Application/obj
      - karly_api_tests_integration_bin_volume:/karly-api/tests/Karly.Api.Tests.Integration/bin
      - karly_api_tests_integration_obj_volume:/karly-api/tests/Karly.Api.Tests.Integration/obj
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_WATCH_RESTART_ON_CHANGES=true
      - ConnectionStrings__KarlyDbContext=Server=database; Database=karly; Username=postgres; Password=${DATABASE_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: postgres:17.1
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    command: >
      bash -c "apt-get update &&
        apt-get install -y postgresql-17-pgvector &&
        docker-entrypoint.sh postgres"

  rabbitmq:
    image: rabbitmq:3.12-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  karly_api_bin_volume:
  karly_api_obj_volume:
  karly_application_bin_volume:
  karly_application_obj_volume:
  karly_api_tests_integration_bin_volume:
  karly_api_tests_integration_obj_volume: